// Package server provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaaW/byBn+K4NpP7QALVFysG21yIccXdddZ72bOF20hmGMyFfSOOTMZA6pisD/XswM",
	"70OWt7biBfLJEcl5r+d5LzI7HPFUcAZMKzzbYRWtICXun28kEA0fQK5BvofPBpS2l4XkAqSm4B6KQUWS",
	"Ck05sz/1VgCeYaUlZUucBXiRkDWX9tYfJSzwDP9hXCkc59rGP/insgAzkkKvIA2pSIiGWxrX7lOmYQmy",
	"8cCaSErmibdvn9ar/MS/ygNZFmAJnw2VEOPZtbcmaDjZtKRXben1TRbgH8oANAMXCdOJn72IFP0CiDKU",
	"0khyFHEJCv0ptX//HKBJGIbu3+glmti/1oJOKFJIudx2xfvrpYZ39LWVOH3xjr628s7o615xbE1jSm6X",
	"fRYvhUGGUd1zsBVL63BpWkPoTXmWz+8g0lbnBV9SNsi6BgcqjohNz+WWGQ40sXHY/GK4JseFhjKlCYug",
	"q6C4gyJumH7GuAZYaS7JsseH/EZpyVlhyZm35KrXkjZCRYiCPZypjOhjz3sgyhekJrKyvA7/JalIHE94",
	"CigFpayw4B725AL6dPpCeel/dznliml8S3Q3aq7QUs5QTDQgwmKkqas7lZHTcDo5CScnp+FV+NfZaTgL",
	"w//YOsNlaiVie/IkP9VJi1aNbiqv/UJ8gfSKKqScK32iHlrOfaK2iB4foCghSt8Kyedw69zqSLFXlSap",
	"sMLs02gFJNErFK0g+vTIEXTWaEmYolb9wSZVR7ouP5JpBXO7ubjiG28FrIHplgEjBFJyWRAfbWiSoDkg",
	"e4qhFUgY9Wkr2nNTlb16AKZ8w0A2ku8aT8PJd3+bhuHpdzjAJE6pSy6qIe2OF9gokOdxn+j8ApGSbH2F",
	"ItrkEhbEJDaM0jBmHw/6AhUZKW2U/MEetJhJrb0uar76CAHWFsqopiShX7zsQstNMDzDHDqY9DevvUNJ",
	"NXwE9ZpTRqQizACru6lXAGc75lXNg2aBm8e8pzN9MnOQDDQo1y7Xk7HgMdqSNEFzoiBGNbvvq1ud+0OT",
	"4OAM+YiT4TASLhB1XX3NoqugO3AYpXmKSjldTpZZ0kRij/uJgfsnpNwr/3Sf8e1k+2jTki1415Sl5Ebc",
	"fi7GrH0h97NYG9XKeJv7D5LUB1hNSNAwruumLSIQGUn19oMV7B262+hXRq/cDOpA4vwThYIKM3xnxNY9",
	"UEVJ0B9hi7PMDX8+SJrqpHjaJccJEdSGHKTy4IejyZgkYuUiwgUw+8AMn47C0dTOr0SvnD1jVzLHZVwE",
	"9+OyBcHNFOcxnuFX9qEPoM+sx7/k7ks/XL/mscvbiDMNzB0mQiQ0csfHd/m85IN7aOh98JXgTPm4TcPw",
	"8ZW0C7mLApoDZUukwFH1xSPqzYfKHsX/vvyIXr3/O/rp8gq9evvu/KcGffDsukac65vsJsDKpCmxozxW",
	"oJFjIip4qclSWcb6bhjgnKFWZB3u8c63w+x+3G2CFrALIkkKGqRydnUbLKK+q+GZo1nF7bL7VmmlpYGg",
	"Fr52Ybn5RrNnRDOH7uEsq08re/jlXxNdVX38KRCvTURPCnpdTzv8RTxQPlf9PoD3xjbmrBby5a06+JYr",
	"roPDEO5nvq5cUKXx/4lIOcjsC085ZXQmkG7AlgXbE2vd7wKnpsldlBwgHqGELykbzkr36sxG64lysfFq",
	"bjgfm6G54MslxIgypEwUgVILkyR2Tl4BiV0z2uEPoE/e+IGqYUy1KRfj1cvdP3+9yr5HPxO9ejn+Hv1D",
	"a3HJnLx2C8qOhv45W5OExuj8LeIS/fyrB78E+IIvlfXfgTzf2taByvGxQLuJMjd6MAcv3O0S5vvif/lj",
	"1xzEjS7NiRIgcq9B+d4xZNAZaP8K7GgVofHG7YCqIEEbyZTLMLtNeYcQcXyk8wSOVykMI0avuKRfbB85",
	"uEicgS6tr8wuHNHcoVlDL4fMbu79taL+jeeJykXfZ6Qn7uJNYgwTIW/kxUb9ldC3Wk+PoFXCwiiwLMln",
	"gsLtg+n3pn4O5WTpo1tVLsY7/zffU2JIwE+UTR6+dddrPLyvnnlBhSmNnvIVYXxxBK25y4xrtOCGPaR8",
	"vK0Hrb9M7C/t+KsnLaJswavi/Q3svb0iP+7eO/V3hX1vA4rTA+8DisR+2BsBWxrqm+UQ4YpN7GjTRLX6",
	"HbZflOvgcXeM3zg5dC2u+NBaAPeufvnWd+4Z9WTFoFr29ix3NN8Gn33gK2s7g/XQYPZRxERDI9S/bTRr",
	"fRuAza0gSm24HPgvFMM3s+478sN2P+N8eRZN+mDYcpv3IOdl2RLoa6eRCZ7hnZBc84gn2Ww83hmZZLOd",
	"4FJn4/UEt75A2evNT5SnYRh2vk8SQYtCbk+MkH0KLbhEMaxHDrRcp1uW8w+VK62FXa+1Fu4TVKUkv9NU",
	"suVGllpycSPkTjtVQvLYRO5LtoSIpymw2DdC53fdicn0L6NwFI4me5WQOJaglIXsJvtfAAAA//+ay7pK",
	"hiYAAA==",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
