// Package server provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPbuBH+Kxi0H9oZWqLszLXVTT7kpee655yvidObNqPxQORKQkICCLCQq2j43zsA",
	"+CKKpKzcxY5vJp8cgcDus/ss9oXMliYyV1KAQEOnW2qSFeTM//OFBobwBvQa9Gv4aMGgW1ZaKtDIwW9K",
	"wSSaK+RSuJ+4UUCn1KDmYkmLiC4ytpbaPfqjhgWd0j+MG4XjUtv4h7CriKhgOfQKQshVxhBueLrznAuE",
	"JejWhjXTnM2zgO+Q1uvyxL/rA0VRRPSHGnLb1ETZjsVukRj+CQgXJOeJliSRGgz5U+7+/jkikziO/b/J",
	"UzJxf2nUAz6HPJd605Wfg1uvVbziz53I0yev+HMn8Jw/75Un1jzl7GbZB3mpLLGCY8/Bol6S8/eQoBN1",
	"KZdcDPLfYqNhS932LBcR1fDRcg0pnb5zR/3GWRHRf1mJ7GFdzoVBJhLoKqiekERagY+Zr4galJote4wo",
	"H9RIzisk5wHJdS+SvgB4DcyE290mR9fr8D+Wq8xTLXMgORjjMEU9AdCRHvLLVfjdDQCfg9Ibhl0LfX7i",
	"UpCUIRAmUoI8d1obOKfx6eQknpycxdfxX6dn8TSO/0sjupA6dxKpO3lSnurE8F5qayvf+UXkguCKG2K8",
	"KX2iPjcLhlu1F5XpEYoyZvBGaTmHG29WR4pbNchy5YS53WQFLMMVSVaQfPjCHvRoUDNhuFN/NKTmSNfk",
	"LwStitHuvVnJ24AC1iBwD8CIgNZSVyFObnmWkTkQd0qQFWgY9WmrqlpblVs9glN5K0C3rtk7ehpPvvvb",
	"aRyffUcjytKcCzqLKEfIu1WZWgP6Iu0TXS4wrdkmZBOGtpSwYDZzbtRWCLc96nNUYrV2XgoHe9gSNnd4",
	"vdeoT1dKgcPCBUfOMv4pyK60zKI7S/9e9JQPyYH7cR9dQrXczVnzVPYUhg92DloAgvHlaj0ZK5mSDcsz",
	"MmcGUlIh609Fno3fBDq6s1cb6qwGerK+bN7V2y3f1qDMSW1Kl7U6jNt+HWwN1yyzxwLcj/i37m6Iheyq",
	"W2pp1c3HqjE55O3Qvex7sAHoLuBnSeoid5cTEqs5bt64vQHj+1t8ZnHlGzHvWyk/cBdBwVf0vVUbv6Ex",
	"XPEfYRNCmJd2I8es2u0j9IQpTiO6Bm0CZ/FoMmaZWnkjpQLhNkzp2SgenbomjuHK4xn7VDSuTVUy9IzO",
	"r75WX6R0Sp+5TW8Az52Hg8WhMwSDz2XqL08iBYLwh5lSGU/88fH7suMI/jrWm6HzNEoKE/x2GsdfXsl+",
	"gvReIHPgYkkM+Oh78gX1lm1Zj+L/XL0lz17/nfx0dU2evXx18VMrfOj03U7gvJsVs4gam+fMtbPUABIf",
	"+eRjSQyypXEpPFSZKJhFZ07kLt3jbSgzxd28uztX0a6YZjkgaONxdQsX4aFa0KkPsya266rWzBSoLUQ7",
	"7tvPB7NvYfaIwsyze3yU4W7BHY6v8Nbiuimm98F4Lf6eSd/VEw01PuWM9PsgPoBtNTt7zNePdsl3seKL",
	"Mgzxfh7yyiU3SH8jI3X/ccg9dePQaSq6DltW0Z45dL8LntqQuyx5QgJDmVxyMXwr/fsj5617uout91PD",
	"97Htmku5XEJKuCDGJgkYs7BZtqERXQFLfTHa0jeAJy9CQ9UC00ygVXv1dPvPX66L78nPDFdPx9+TfyCq",
	"K+Hl7Zeg4sHYvxBrlvGUXLwkUpOffwnk1wRfyqVx9nuS5xtXOkjdPlZst1mWFgfv4KV/XNN8l/+vfuzC",
	"IdJiDSfJgOmDgMpxYQjQOWB4tfRgGaH1JuuIrKABrRbG3zA3BAWDCPPxyOcZPFymsIJZXEnNP7k6cnSS",
	"OAes0TewK0NQejZ32CspmxXRQK7Y/eRwT+mi76vGPVfxdmAMB0JZyKtB+Cux77SePYBWDQtrwEVJ2RNU",
	"Zh8dfi92z5EyWPrCrUkX4234W84pKWQQOsp2HL706ztxeFc+C4IqKK2a8hVpfPIAWkuThUSykFZ8Tvp4",
	"ueu0/jRxOLXTr35pCRcL2STvb2QfrBXlcf/eqb8qHHobUJ0eeB9QXezPeyPgUsPuZDkUcNUk9mDdRDP6",
	"HTdf1OPgw84Yv7Jz6CJu4mFvADw4+pVT30WIqHtLBs2wd2C44+U0+Ogd36DtNNZDjdlblTKElqt/XWu2",
	"90ofbm8UM+ZW6oH/RzD8sOcd+XGzn/W2PIoifTRtJeYDzAVZLgWG3Gl1Rqd0q7REmcismI7HW6uzYrpV",
	"UmMxXk9oRFvfk9x6+9PfWRzHne9+TPEqkbsTI+J2kYXUJIX1yJNW6vTDcvkBcIWo3HiNqAydRTtKyidt",
	"JRtpda2lFDci/rRXpbRMbeK/EGtIZJ6DSEMh9HbvGjE5/csoHsWjyUElLE01GP9tb1b8PwAA///Y8DmL",
	"FSUAAA==",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
