// Package common provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package common

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaaW/byBn+K4NpP7QALVFysG21yIccXdddZ72bOF20hmGMyFfSOOTMZA6pisD/XswM",
	"70OWt7biBfLJEcl5r+d5LzI7HPFUcAZMKzzbYRWtICXun28kEA0fQK5BvofPBpS2l4XkAqSm4B6KQUWS",
	"Ck05sz/1VgCeYaUlZUucBXiRkDWX9tYfJSzwDP9hXCkc59rGP/insgAzkkKvIA2pSIiGWxrX7lOmYQmy",
	"8cCaSErmibdvn9ar/MS/ygNZFmAJnw2VEOPZtbcmaDjZtKRXben1TRbgH8oANAMXCdOJn72IFP0CiDKU",
	"0khyFHEJCv0ptX//HKBJGIbu3+glmti/1oJOKFJIudx2xfvrpYZ39LWVOH3xjr628s7o615xbE1jSm6X",
	"fRYvhUGGUd1zsBVL63BpWkPoTXmWz+8g0lbnBV9SNsi6BgcqjohNz+WWGQ40sXHY/GK4JseFhjKlCYug",
	"q6C4gyJumH7GuAZYaS7JsseH/EZpyVlhyZm35KrXkjZCRYiCPZypjOhjz3sgyhekJrKyvA7/JalIHE94",
	"CigFpayw4B725AL6dPpCeel/dznliml8S3Q3aq7QUs5QTDQgwmKkqas7lZHTcDo5CScnp+FV+NfZaTgL",
	"w//YOsNlaiVie/IkP9VJi1aNbiqv/UJ8gfSKKqScK32iHlrOfaK2iB4PKqpxLCFK3wrJ53Dr/OqIsVeV",
	"Jqmw0uzTaAUk0SsUrSD69MghdNZoSZiiVv3BJlVHuj4/kmkFdbvJuOIbbwWsgemWASMEUnJZMB9taJKg",
	"OSB7iqEVSBj1aSv6c1OVvXoAe/iGgWxk3zWehpPv/jYNw9PvcIBJnFKXXVRD2p0vsFEgz+M+0fkFIiXZ",
	"+hJFtMklLIhJbBilYcw+HvQFKjJS2ij5gz1oMZNae13UfPkRAqwtlFFNSUK/eNmFlptgeIg5dDLp7157",
	"p5Jq+gjqRaeMSEWYAVZ3U68AzrbMq5oHzQo353FPa/pk5iAZaFCuX64nY8FjtCVpguZEQYxqdt9XuDr3",
	"h0bBwSHyEUfDYSRcIOq6+rpFW0E3nnucSAzcP+jktvmnDzGhJ98iozRPUelKNy3KRH1INPsS9qNNbbbg",
	"3UAsJTfi9nMxq+1T5Ae6NjOq0Nn68SBJfaDXhAQN47pBtoUIIiOp3n6wgr1Ddxv9yuiVG2RdlDn/RKGg",
	"0wzfGbF1D1RREvRH2OIscxOkD5KmOimedgl2QgS1gINUHr1wNBmTRKxcRLgAZh+Y4dNROJraIZjolbNn",
	"7MruuIyL4H7mtiC4weQ8xjP8yj70AfSZ9fiX3H3pJ/TXee5HnGlg7jARIqGROz6+y4cuH9xDQ++DrwRn",
	"ysdtGoaPr6TdDFwU0BwoWyIFLlFePKLefDLtUfzvy4/o1fu/o58ur9Crt+/Of2rQB8+ua8S5vsluAqxM",
	"mhK7D2AFGjkmooKXmiyVZazvqAHOGWpF1uEe73xLze7H3SZoAbsgkqSgQSpnV7dJI+o7I545mlXcLjt4",
	"lVZaGghq4WuXtZtvNHtGNHPoHs6y+sSzh1/+XdNVNQs8BeK1qepJQa/raYe/iAfKZ7PfB/De2Mas1kK+",
	"vFUH33LFdXAYwv3M15ULqjT+PxE5aBIpp4zOBNIN2LJge2Kt+13g1DS5i5IDxCOU8CVlw1np3r/ZaD1R",
	"Ljbe7w3nYzM0F3y5hBhRhpSJIlBqYZLEztorILFrRjv8AfTJGz9QNYyptu1ivHq5++evV9n36GeiVy/H",
	"36N/aC0umZPXbkHZ0dA/Z2uS0Bidv0Vcop9/9eCXAF/wpbL+O5DnW9s6UDk+Fmg3UeZGD+bghbtdwnxf",
	"/C9/7JqDuNGlOVECRO41KF8chgw6A+3fox2tIjRe2x1QFSRoI5lyGWbXIe8QIo6PNF9ujsMVw4jRKy7p",
	"F9tHDi4SZ6BL6yuzC0c0d2jW0Mshs9t/f62ofyh6onLR9y3qibt4kxjDRMgbebESfyX0rdbTI2iVsDAK",
	"LEvymaBw+2D6vamfQzlZ+uhWlYvxzv/N95QYEvATZZOHb931Gg/vq2deUGFKo6d8RRhfHEFr7jLjGi24",
	"YQ8pH2/rQesvE/tLO/7qSYsoW/CqeH8De2+vyI+79079XWHf24Di9MD7gCKxH/ZGwJaG+mY5RLhiEzva",
	"NFGtfoftF+U6eNwd4zdODl2LKz60FsC9q1++9Z17Rj1ZMaiWvT3LHc23wWcf+MrazmA9NJh9FDHR0Aj1",
	"bxvNWl8mYHMriFIbLgf+H8bwzaz7jvyw3c84X55Fkz4YttzmPch5WbYE+tppZIJneCck1zziSTYbj3dG",
	"JtlsJ7jU2Xg9wa2vWPZ68zPnaRiGnW+cRNCikNsTI2SfQgsuUQzrkQMt1+mW5fxj50prYddrrYX7jFUp",
	"ye80lWy5kaWWXNwIudNOlZA8NpH7Gi4h4mkKLPaN0Pldd2Iy/csoHIWjyV4lJI4lKGUhu8n+FwAA///Q",
	"YNplyyYAAA==",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
