// Package common provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package common

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaaW/byBn+K4NpP7QALVFysG21yIccXdddZ72bOF20hmGMyFfSOOTMZA6pisD/XswM",
	"70OWt7biBfLJEcl5r+d5LzI7HPFUcAZMKzzbYRWtICXun28kEA0fQK5BvofPBpS2l4XkAqSm4B6KQUWS",
	"Ck05sz/1VgCeYaUlZUucBXiRkDWX9tYfJSzwDP9hXCkc59rGP/insgAzkkKvIA2pSIiGWxrX7lOmYQmy",
	"8cCaSErmibdvn9ar/MS/ygNZFmAJnw2VEOPZtbcmaDjZtKRXben1TRbgH8oANAMXCdOJn72IFP0CiDKU",
	"0khyFHEJCv0ptX//HKBJGIbu3+glmti/1oJOKFJIudx2xfvrpYZ39LWVOH3xjr628s7o615xbE1jSm6X",
	"fRYvhUGGUd1zsBVL63BpWkPoTXmWz+8g0lbnBV9SNsi6BgcqjohNz+WWGQ40sXHY/GK4JseFhjKlCYug",
	"q6C4gyJumH7GuAZYaS7JsseH/EZpyVlhyZm35KrXkjZCRYiCPZypjOhjz3sgyhekJrKyvA7/JalIHE94",
	"CigFpayw4B725AL6dPpCeel/dznliml8S3Q3aq7QUs5QTDQgwmKkqas7lZHTcDo5CScnp+FV+NfZaTgL",
	"w//YOsNlaiVie/IkP9VJi1aNbiqv/UJ8gfSKKqScK32iHlrOfaK2iB4foCghSt8Kyedw69zqSLFXlSap",
	"sMLs02gFJNErFK0g+vTIEXTWaEmYolb9wSZVR7ouP5JpBXO7ubjiG28FrIHplgEjBFJyWRAfbWiSoDkg",
	"e4qhFUgY9Wkr2nNTlb16AKZ8w0A2ku8aT8PJd3+bhuHpdzjAJE6pSy6qIe2OF9gokOdxn+j8ApGSbH2F",
	"ItrkEhbEJDaM0jBmHw/6AhUZKW2U/MEetJhJrb0uar76CAHWFsqopiShX7zsQstNMDzDHDqY9DevvUNJ",
	"NXwE9ZpTRqQizACru6lXAGc75lXNg2aBm/O4pzN9MnOQDDQo1y7Xk7HgMdqSNEFzoiBGNbvvq1ud+0OT",
	"4OAM+YiT4TASLhB1XX3Noq2gG889TiQG7p9zctv804eY0JNvkVGap6h0pZsWZaI+JJp9CfvRpjZb8G4g",
	"lpIbcfu5GNX2KfLzXJsZVehs/XiQpD7Qa0KChnHdINtCBJGRVG8/WMHeobuNfmX0ys2xLsqcf6JQ0GmG",
	"74zYugeqKAn6I2xxlrkB0gdJU50UT7sEOyGCWsBBKo9eOJqMSSJWLiJcALMPzPDpKBxN7QxM9MrZM3Zl",
	"d1zGRXA/clsQ3FxyHuMZfmUf+gD6zHr8S+6+9AP66zz3I840MHeYCJHQyB0f3+Uzlw/uoaH3wVeCM+Xj",
	"Ng3Dx1fSbgYuCmgOlC2RApcoLx5Rbz6Y9ij+9+VH9Or939FPl1fo1dt35z816INn1zXiXN9kNwFWJk2J",
	"XQewAo0cE1HBS02WyjLWd9QA5wy1Iutwj3e+pWb3424TtIBdEElS0CCVs6vbpBH1nRHPHM0qbpcdvEor",
	"LQ0EtfC1y9rNN5o9I5o5dA9nWX3i2cMv/6rpqpoFngLx2lT1pKDX9bTDX8QD5bPZ7wN4b2xjVmshX96q",
	"g2+54jo4DOF+5uvKBVUa/5+IHDSJlFNGZwLpBmxZsD2x1v0ucGqa3EXJAeIRSviSsuGsdK/fbLSeKBcb",
	"r/eG87EZmgu+XEKMKEPKRBEotTBJYmftFZDYNaMd/gD65I0fqBrGVNt2MV693P3z16vse/Qz0auX4+/R",
	"P7QWl8zJa7eg7Gjon7M1SWiMzt8iLtHPv3rwS4Av+FJZ/x3I861tHagcHwu0myhzowdz8MLdLmG+L/6X",
	"P3bNQdzo0pwoASL3GpQvDkMGnYH2r9GOVhEab+0OqAoStJFMuQyz65B3CBHHR5ovN8fhimHE6BWX9Ivt",
	"IwcXiTPQpfWV2YUjmjs0a+jlkNntv79W1L8TPVG56PsU9cRdvEmMYSLkjbxYib8S+lbr6RG0SlgYBZYl",
	"+UxQuH0w/d7Uz6GcLH10q8rFeOf/5ntKDAn4ibLJw7fueo2H99UzL6gwpdFTviKML46gNXeZcY0W3LCH",
	"lI+39aD1l4n9pR1/9aRFlC14Vby/gb23V+TH3Xun/q6w721AcXrgfUCR2A97I2BLQ32zHCJcsYkdbZqo",
	"Vr/D9otyHTzujvEbJ4euxRUfWgvg3tUv3/rOPaOerBhUy96e5Y7m2+CzD3xlbWewHhrMPoqYaGiE+reN",
	"Zq0vE7C5FUSpDZcD/w1j+GbWfUd+2O5nnC/PokkfDFtu8x7kvCxbAn3tNDLBM7wTkmse8SSbjcc7I5Ns",
	"thNc6my8nuDWVyx7vfmZ8zQMw843TiJoUcjtiRGyT6EFlyiG9ciBlut0y3L+sXOltbDrtdbCfcaqlOR3",
	"mkq23MhSSy5uhNxpp0pIHpvIfQ2XEPE0BRb7Ruj8rjsxmf5lFI7C0WSvEhLHEpSykN1k/wsAAP//wztN",
	"NMomAAA=",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
