// Code generated by entc, DO NOT EDIT.

package event

import (
	"time"
)

const (
	// Label holds the string label denoting the event type in the database.
	Label = "event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeServer holds the string denoting the server edge name in mutations.
	EdgeServer = "server"

	// Table holds the table name of the event in the database.
	Table = "events"
	// UserTable is the table the holds the user relation/edge. The primary key declared below.
	UserTable = "event_user"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// ServerTable is the table the holds the server relation/edge. The primary key declared below.
	ServerTable = "event_server"
	// ServerInverseTable is the table name for the Server entity.
	// It exists in this package in order to avoid circular dependency with the "server" package.
	ServerInverseTable = "servers"
)

// Columns holds all SQL columns for event fields.
var Columns = []string{
	FieldID,
	FieldMessage,
	FieldCreatedAt,
}

var (
	// UserPrimaryKey and UserColumn2 are the table columns denoting the
	// primary key for the user relation (M2M).
	UserPrimaryKey = []string{"event_id", "user_id"}
	// ServerPrimaryKey and ServerColumn2 are the table columns denoting the
	// primary key for the server relation (M2M).
	ServerPrimaryKey = []string{"event_id", "server_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
)
