// Code generated by entc, DO NOT EDIT.

package user

import (
	"time"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserPw holds the string denoting the user_pw field in the database.
	FieldUserPw = "user_pw"
	// FieldQuotaInstance holds the string denoting the quota_instance field in the database.
	FieldQuotaInstance = "quota_instance"
	// FieldQuotaCPU holds the string denoting the quota_cpu field in the database.
	FieldQuotaCPU = "quota_cpu"
	// FieldQuotaMemory holds the string denoting the quota_memory field in the database.
	FieldQuotaMemory = "quota_memory"
	// FieldQuotaNvidiaGpu holds the string denoting the quota_nvidia_gpu field in the database.
	FieldQuotaNvidiaGpu = "quota_nvidia_gpu"
	// FieldQuotaStorage holds the string denoting the quota_storage field in the database.
	FieldQuotaStorage = "quota_storage"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"

	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// EdgeServers holds the string denoting the servers edge name in mutations.
	EdgeServers = "servers"
	// EdgeTemplates holds the string denoting the templates edge name in mutations.
	EdgeTemplates = "templates"

	// Table holds the table name of the user in the database.
	Table = "users"
	// EventsTable is the table the holds the events relation/edge. The primary key declared below.
	EventsTable = "event_user"
	// EventsInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventsInverseTable = "events"
	// ServersTable is the table the holds the servers relation/edge. The primary key declared below.
	ServersTable = "user_servers"
	// ServersInverseTable is the table name for the Server entity.
	// It exists in this package in order to avoid circular dependency with the "server" package.
	ServersInverseTable = "servers"
	// TemplatesTable is the table the holds the templates relation/edge. The primary key declared below.
	TemplatesTable = "user_templates"
	// TemplatesInverseTable is the table name for the Template entity.
	// It exists in this package in order to avoid circular dependency with the "template" package.
	TemplatesInverseTable = "templates"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldUserPw,
	FieldQuotaInstance,
	FieldQuotaCPU,
	FieldQuotaMemory,
	FieldQuotaNvidiaGpu,
	FieldQuotaStorage,
	FieldCreatedAt,
	FieldDeletedAt,
}

var (
	// EventsPrimaryKey and EventsColumn2 are the table columns denoting the
	// primary key for the events relation (M2M).
	EventsPrimaryKey = []string{"event_id", "user_id"}
	// ServersPrimaryKey and ServersColumn2 are the table columns denoting the
	// primary key for the servers relation (M2M).
	ServersPrimaryKey = []string{"user_id", "server_id"}
	// TemplatesPrimaryKey and TemplatesColumn2 are the table columns denoting the
	// primary key for the templates relation (M2M).
	TemplatesPrimaryKey = []string{"user_id", "template_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultQuotaInstance holds the default value on creation for the quota_instance field.
	DefaultQuotaInstance int
	// DefaultQuotaCPU holds the default value on creation for the quota_cpu field.
	DefaultQuotaCPU int
	// DefaultQuotaMemory holds the default value on creation for the quota_memory field.
	DefaultQuotaMemory int
	// DefaultQuotaNvidiaGpu holds the default value on creation for the quota_nvidia_gpu field.
	DefaultQuotaNvidiaGpu int
	// DefaultQuotaStorage holds the default value on creation for the quota_storage field.
	DefaultQuotaStorage int
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
)
