// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Server is the predicate function for server builders.
type Server func(*sql.Selector)

// Template is the predicate function for template builders.
type Template func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
